/- Generated by `python3 hardware/gfx1151/lean/generate.py`. Do not edit. -/
import Kelana.Hardware.Catalogue.VALU
import Kelana.Hardware.Catalogue.VMEM
import Kelana.Hardware.Catalogue.SALU
import Kelana.Hardware.Catalogue.Other

namespace Kelana.Hardware.Catalogue

/-- Source hashes, counts and the command that regenerates this catalogue. -/
def provenance : Provenance := ⟨
  "AMD RDNA 3.5",
  "2026-02-20",
  "1.1.1",
  "c36b6d79b1e940d74107221c985f5a7fde248025da251d2c6ef756c4cd31391a",
  "af07d5a7b1bbcf27355f6b38405bfae83ad729acc512c0a77c20beb257978727",
  "154dce7f851ffa1ddba023a57263a1159b88bdd4841e166a6230113cd2f67100",
  "0dce785cd69b9aabfb0701f8e86f0b60c88f8eb29c22b4854497dfd02cbba57f",
  "python3 hardware/gfx1151/lean/generate.py",
  1208,
  5056⟩

/-- Every architecture-level instruction name of AMD RDNA 3.5, with Kelana's status
for each. Membership is an architecture claim; see `Instruction.gfx1151Probes` for
what the installed gfx1151 assembler was observed to accept. -/
def all : Array Instruction :=
  VALU.all ++ VMEM.all ++ SALU.all ++ Other.all

/-- Questions the pinned sources leave open, kept as data so that a meaning Kelana
does not have stays visible instead of turning into a default. -/
def openQuestions : Array String := #[
  "V_DOT4_I32_IU8 and V_DOT8_I32_IU4 accept CLAMP on gfx1151, but the section 16.10 pseudocode gives no saturation step, and the section 7.1 CLMP description ('Signed integer arithmetic: clamp result to [min_int, +max_int]') does not say whether the sum is formed exactly before clamping or wraps in the 32-bit accumulator first. Unmodeled.",
  "Section 7.5 lists OP_SEL and OP_SEL_HI as available 'on src0/1' for DOT4_I32_IU8 and DOT8_I32_IU4, while the instruction pseudocode reads all 32 bits of each source and contains no OP_SEL term. What a non-default setting does to a 32-bit-source dot is unresolved; only the assembler's default encoding is modeled.",
  "NEG[2] and NEG_HI are encodable on the VOP3P dot opcodes and appear in no dot pseudocode. Unmodeled.",
  "Without CLAMP the manual writes the dot accumulator as a 32-bit signed 'tmp' with no statement about overflow. Kelana models the wrapping two's-complement result, which is order-independent; whether the hardware instead saturates or holds a wider intermediate is unverified. Kelana.Hardware.Lemmas.dot4_eq_exact_sum bounds the claim to non-overflowing inputs.",
  "V_PERM_B32's note says selects 12 and 13 return padding of 0 and 1 bits, while its pseudocode returns 0xff for every selector >= 13. Kelana follows the pseudocode; the note is silent about 14..255.",
  "The manual's V_DOT4_I32_IU8 prose calls both inputs 'unsigned 8-bit' in the same paragraph that defines the NEG signedness control, and the XML description says 'signed or unsigned'. Kelana follows the pseudocode and the NEG control.",
  "Native V_WMMA_F32_16X16X16_F16 on this gfx1151 part returns -0x1.000002p+0 (-1.000000119...) for A = [-1,-1,0,...], B = [1,0,0,...], C = 0, so it is not exact even on exactly representable small integer operands. The WMMA floating-point semantics and any error bound are unresolved; see research/ffn/packed-wmma/NOTES.md and integer_probe.cpp. No Lean definition in this layer claims a WMMA meaning, and the integer algebra in Kelana/PairedWMMA.lean is not a proof about the native instruction.",
  "Execution cost is not a function of instruction count and is not represented in this layer. The measured gfx1151 result in research/ffn/packed-wmma/NOTES.md is that the IU8 and F16 WMMA issue at the same rate, which contradicts counting-based cost estimates."]

end Kelana.Hardware.Catalogue
