/- Generated by `python3 hardware/gfx1151/lean/generate.py`. Do not edit.

Elaborating this module fails if a `Status.laneBitVec` declaration named in the
catalogue does not exist, so the status table cannot drift from the Lean meanings. -/
import Kelana.Hardware.IntOps

namespace Kelana.Hardware.Catalogue.Linkage

example := @Kelana.Hardware.v_add_nc_u32
example := @Kelana.Hardware.v_sub_nc_u32
example := @Kelana.Hardware.v_mul_lo_u32
example := @Kelana.Hardware.v_lshlrev_b32
example := @Kelana.Hardware.v_lshrrev_b32
example := @Kelana.Hardware.v_ashrrev_i32
example := @Kelana.Hardware.v_and_b32
example := @Kelana.Hardware.v_or_b32
example := @Kelana.Hardware.v_xor_b32
example := @Kelana.Hardware.v_lshl_or_b32
example := @Kelana.Hardware.v_bfe_u32
example := @Kelana.Hardware.v_perm_b32
example := @Kelana.Hardware.v_dot4_i32_iu8
example := @Kelana.Hardware.v_dot8_i32_iu4

end Kelana.Hardware.Catalogue.Linkage
