#!/usr/bin/env python3
"""Export checked rational duals as concrete instances of the Lean theorem.

Scale each constraint row, then the dual weights, to integers. Scaling rows
without inversely scaling their prices would silently change the certificate.
The generated theorems remain conditional on the semantic/service inequalities.
"""
import argparse
from fractions import Fraction
import json
from math import lcm
from pathlib import Path

from certificates import digest, rational, require, verify_dual

HERE = Path(__file__).resolve().parent


def integer_rows(rows):
    scales = [lcm(*(v.denominator for v in row)) for row in rows]
    return [[int(v*s) for v in row] for row, s in zip(rows, scales)], scales


def instance(case):
    model, problem, family = (case[k] for k in ("model", "problem", "family"))
    dual = case["proposal"]["dual"]
    require(verify_dual(model, problem, family, dual)["valid"], "cannot export an invalid dual")
    if "semantic_source" in case:
        from potential_bridge import verify_source
        verify_source(case)
    ops = family["allowed_operations"]
    cuts = [c for c in family["obligations"] if rational(dual["lambda"].get(c["id"], 0)) > 0]
    resources = [r for r in model["resources"] if rational(dual["mu"].get(r, 0)) > 0]
    ar, asc = integer_rows([[rational(c["coefficients"].get(op, 0)) for op in ops]+[rational(c["minimum"])] for c in cuts])
    dr, dsc = integer_rows([[rational(model["operations"][op]["demand"].get(r, 0)) for op in ops]+[rational(model["resources"][r])] for r in resources])
    lam = [rational(dual["lambda"].get(c["id"], 0))/s for c, s in zip(cuts, asc)]
    mu = [rational(dual["mu"].get(r, 0))/s for r, s in zip(resources, dsc)]
    scale = lcm(*(v.denominator for v in lam+mu))
    weights, prices = [int(v*scale) for v in lam], [int(v*scale) for v in mu]
    a, b = [row[:-1] for row in ar], [row[-1] for row in ar]
    d, capacity = [row[:-1] for row in dr], [row[-1] for row in dr]
    work = sum(w*x for w, x in zip(weights, b))
    service = sum(w*x for w, x in zip(prices, capacity))
    require(service > 0, "scaled certificate has zero service")
    expected_work = sum(rational(dual["lambda"].get(c["id"], 0))*rational(c["minimum"]) for c in cuts)
    expected_service = sum(rational(dual["mu"].get(r, 0))*rational(model["resources"][r]) for r in resources)
    require(Fraction(work, service) == expected_work/expected_service, "row scaling changed the bound")
    return {"A": a, "b": b, "D": d, "c": capacity, "lambda": weights, "mu": prices,
            "work": work, "service": service, "case_sha256": digest(case)}


def trim_zeros(values):
    end = len(values)
    while end and values[end-1] == 0:
        end -= 1
    return values[:end]


def lean_list(value):
    return "["+", ".join(lean_list(v) if isinstance(v, list) else str(v) for v in value)+"]"


def render(cases):
    text = ["import Kelana.ResourceBounds", "", "/-! Generated by resource-bounds/core/export_lean.py.",
            "Concrete dual arithmetic only. Feasible remains a semantic/service premise.",
            "Zero-priced rows are omitted; remaining rows are scaled to integers.",
            "No program semantics, schedule or native rate is inferred here. -/", "",
            "namespace Kelana.ResourceCertificates", "open Kelana.ResourceBounds", "",
            "set_option maxRecDepth 8192", "set_option maxHeartbeats 800000", ""]
    for i, case in enumerate(cases):
        x = instance(case)
        name = f"case{i}"
        text += [f"-- {case['name']}; SHA256 {x['case_sha256']}",
                 f"def {name}Cuts : Obligations := ⟨{lean_list(x['A'])}, {lean_list(x['b'])}⟩",
                 f"def {name}Machine : Machine := ⟨⟨\"declared model ticks\"⟩, {lean_list(x['D'])}, {lean_list(x['c'])}, 0⟩",
                 f"def {name}Dual : Certificate := ⟨{lean_list(trim_zeros(x['lambda']))}, {lean_list(trim_zeros(x['mu']))}⟩",
                 f"theorem {name}_checked :",
                 f"    {name}Dual.check {name}Cuts {name}Machine = true ∧",
                 f"    {name}Dual.work {name}Cuts = {x['work']} ∧",
                 f"    {name}Dual.service {name}Machine = {x['service']} := by decide",
                 f"theorem {name}_bound (e : Execution) (h : Feasible {name}Cuts {name}Machine e) :",
                 f"    {x['work']} ≤ (e.ticks : Int) * {x['service']} := by",
                 f"  have bound := {name}Dual.bound {name}_checked.1 h",
                 f"  rw [{name}_checked.2.1, {name}_checked.2.2] at bound",
                 "  exact bound", ""]
    text += ["end Kelana.ResourceCertificates", ""]
    return "\n".join(text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("artifacts", type=Path, nargs="*")
    parser.add_argument("--out", type=Path, default=HERE.parents[3] / "Kelana" / "ResourceCertificates.lean")
    args = parser.parse_args()
    paths = args.artifacts or [HERE / "results.json", HERE / "potential-results.json"]
    cases = [case for path in paths for case in json.loads(path.read_text())["cases"] if "proposal" in case]
    require(cases, "no duals to export")
    args.out.write_text(render(cases))
    print(args.out)
