import Kelana

#print axioms Kelana.Halo.decode_encode
#print axioms Kelana.PeelLanes.three_peels
#print axioms Kelana.PeelLanes.maximum_lanes
#print axioms Kelana.two_ternary_dots_radix64
#print axioms Kelana.every_dot_result_reachable
#print axioms Kelana.minimum_radix_is_33
#print axioms Kelana.no_three_digit_separating_byte_radix
#print axioms Kelana.no_byte_radix_decoder16
#print axioms Kelana.Nibble.two_iu4_mac
#print axioms Kelana.Nibble.gather_two_trits
#print axioms Kelana.Amortization.recurring_cost_limit
#print axioms Kelana.Information.activation_batch_cut
#print axioms Kelana.Information.iu8_optimal_in_mixed_port_class
#print axioms Kelana.Matrix.prepared_iu8_correct
#print axioms Kelana.Matrix.universal_matrix_cut
#print axioms Kelana.Toy2.chosen_fits
#print axioms Kelana.Toy2.packed_correct
#print axioms Kelana.Toy2.baseline_equals_packed
#print axioms Kelana.Toy2.strictly_cheaper
#print axioms Kelana.Toy2.load_cost_cannot_erase_saving
#print axioms Kelana.Toy2.fused_correct
#print axioms Kelana.Toy2.no_variable_signedness_dot8
#print axioms Kelana.PairedWMMA.paired_block_correct
#print axioms Kelana.PairedWMMA.sparse_paired_block_correct
#print axioms Kelana.Composition.chain
#print axioms Kelana.Composition.factors_iff
#print axioms Kelana.Composition.operation_descends_iff
#print axioms Kelana.Composition.compound_closure_without_stage_closure
#print axioms Kelana.PackedChains.capacity_iff
#print axioms Kelana.PackedChains.profitable_window
#print axioms Kelana.CompositionCost.best_is_optimal
#print axioms Kelana.FFNBoundaries.quantizer_certificate_composes
#print axioms Kelana.Hardware.plain_add_sub_cancels
#print axioms Kelana.Hardware.bfe_lshl_or_nibble
#print axioms Kelana.Hardware.dot4_eq_exact_sum
#print axioms Kelana.FFNPairedMap.spanning_consumer_correct
#print axioms Kelana.TernaryTable.chain_decodes
#print axioms Kelana.TernaryTable.lookup_antipodal
#print axioms Kelana.TernaryTable.signed_table_recovery
#print axioms Kelana.GuidedPacking.guided_dot_decodes
#print axioms Kelana.Approximation.adjacent_rounding_unbiased
#print axioms Kelana.Approximation.adjacent_rounding_energy
#print axioms Kelana.Approximation.adjacent_variance_bound
#print axioms Kelana.Approximation.square_bias
#print axioms Kelana.Approximation.rounding_creates_bias
#print axioms Kelana.Approximation.energy_quadruples
#print axioms Kelana.Approximation.correlation_changes_accumulation
#print axioms Kelana.ConsumerGeometry.invisible_move
#print axioms Kelana.ConsumerGeometry.reaches_face
#print axioms Kelana.ConsumerGeometry.nearest_input_can_lose
#print axioms Kelana.ConsumerGeometry.consumer_error_energy
#print axioms Kelana.ConsumerGeometry.correlated_error_disappears
#print axioms Kelana.ConsumerGeometry.scale_fit_square
#print axioms Kelana.ConsumerGeometry.scale_fit_lower_numerator
#print axioms Kelana.TriplePacking.decode
#print axioms Kelana.TriplePacking.operand_bound
#print axioms Kelana.TriplePacking.accumulator_bound
#print axioms Kelana.TriplePacking.dot_pack
#print axioms Kelana.TriplePacking.dot_decodes
#print axioms Kelana.TriplePacking.wide_operand_bound
#print axioms Kelana.TriplePacking.wide_separates
#print axioms Kelana.TriplePacking.wide_margin_upper_bound
#print axioms Kelana.TriplePacking.wide_margin_attained
#print axioms Kelana.DirectConsumer.product_word_correct
#print axioms Kelana.DirectConsumer.product_i24_correct
#print axioms Kelana.DirectConsumer.relu_correct
#print axioms Kelana.DirectConsumer.downstream_correct
#print axioms Kelana.DirectConsumer.downstream_128
#print axioms Kelana.DirectConsumer.wrap_invisible
#print axioms Kelana.DirectConsumer.packed_polynomial
#print axioms Kelana.DirectConsumer.word_polynomial
#print axioms Kelana.DirectConsumer.word_derivative_correct
#print axioms Kelana.DirectConsumer.polynomial_taylor
#print axioms Kelana.DirectConsumer.mul24_quotient
#print axioms Kelana.DirectConsumer.native_polynomial24
#print axioms Kelana.DirectConsumer.native_derivative24_correct
#print axioms Kelana.DirectConsumer.silu_polynomial_small
#print axioms Kelana.DirectConsumer.product_only_insufficient
#print axioms Kelana.DeferredCarrier.certified_run
#print axioms Kelana.DeferredCarrier.certified_partition
#print axioms Kelana.DeferredCarrier.single_block_safe
#print axioms Kelana.DeferredCarrier.longest_monotone
#print axioms Kelana.DeferredCarrier.greedy_dominates
#print axioms Kelana.DeferredCarrier.noisy_separation
#print axioms Kelana.DeferredCarrier.parity_assisted_decode
#print axioms Kelana.DeferredCarrier.expanded_range_needs_side_information
#print axioms Kelana.DeferredCarrier.support_parity
#print axioms Kelana.ContractedFFN.contracted_network
#print axioms Kelana.ContractedFFN.coefficients_unique
#print axioms Kelana.ContractedFFN.outside_domain_counterexample
#print axioms Kelana.ContractedToy.dot_replaces_network
#print axioms Kelana.TritObserver.observer_compilation
#print axioms Kelana.ContractedToy.two_instructions_replace_network
#print axioms Kelana.ObserverDescent.observed_gain
#print axioms Kelana.ObserverDescent.coupled_gain
#print axioms Kelana.ObserverDescent.approximate_observer_certificate
#print axioms Kelana.ObserverDescent.nearest_source_codes_can_lose
#print axioms Kelana.RegisterObserver.offline_bias_correction
#print axioms Kelana.RegisterObserver.eight_pairs_fit_byte
#print axioms Kelana.RegisterObserver.four_byte_decode
#print axioms Kelana.ScaledTrit.scaled_operand
#print axioms Kelana.ScaledTrit.absorb_projection
#print axioms Kelana.SevenProduct.seven_correct
#print axioms Kelana.SevenProduct.scaled_seven
#print axioms Kelana.SevenProduct.a3_sum_difference_fit
#print axioms Kelana.SevenProduct.a4_can_escape_i4
#print axioms Kelana.ScaledTritCodec.spread_fields
#print axioms Kelana.ScaledTritCodec.selector_interleave
#print axioms Kelana.ScaledTritCodec.matches_scaled_operand
#print axioms Kelana.TernaryAlgebra.normalize_correct
#print axioms Kelana.TernaryAlgebra.coefficients_unique
#print axioms Kelana.TernaryAlgebra.interpolate_correct
#print axioms Kelana.TernaryAlgebra.normal_equal_iff
#print axioms Kelana.TernaryAlgebra.closure_certificate
#print axioms Kelana.TernaryAlgebra.substitute_normal_identity
#print axioms Kelana.TernaryAlgebra.unrestricted_substitution_fails
#print axioms Kelana.TernaryAlgebra.integer_one_hot_not_polynomial
#print axioms Kelana.TernaryAlgebra.even_coefficient_vanishes
#print axioms Kelana.TernaryFFN.network_reflection
#print axioms Kelana.TernaryFFN.canonical_even_part
#print axioms Kelana.TernaryFFN.absent_even_coefficient
#print axioms Kelana.ObserverDescent.nearest_diagonal_nonnegative
#print axioms Kelana.ObserverDescent.nearest_gain_requires_correlation
