-- Generated by research/ffn/contracted-map/check.py.
import Kelana.ContractedFFN
import Kelana.Hardware.IntOps
import Kelana.TritObserver

namespace Kelana.ContractedToy
open Kelana.ContractedFFN Kelana.Hardware

def weights : List (Unit Int) := [
  ⟨0, 1, -1, 0, 1⟩,
  ⟨0, 0, 0, -1, 0⟩,
  ⟨1, 1, -1, -1, 0⟩,
  ⟨0, -1, 0, 0, -1⟩,
  ⟨-1, 0, -1, -1, 0⟩,
  ⟨-1, -1, -1, 0, 1⟩,
  ⟨1, 0, -1, 0, 0⟩,
  ⟨-1, 0, 1, -1, 1⟩,
  ⟨-1, 1, -1, -1, -1⟩,
  ⟨0, 1, -1, 0, 0⟩,
  ⟨1, 0, 0, 0, -1⟩,
  ⟨-1, 1, 1, 1, -1⟩,
  ⟨1, -1, 1, 0, 0⟩,
  ⟨1, 1, -1, 0, 1⟩,
  ⟨-1, 0, -1, 0, -1⟩,
  ⟨-1, 1, -1, -1, 1⟩,
  ⟨-1, 1, -1, -1, 0⟩,
  ⟨-1, 0, -1, 1, 0⟩,
  ⟨0, 0, -1, 1, 0⟩,
  ⟨1, 1, -1, -1, -1⟩,
  ⟨0, 0, -1, 0, -1⟩,
  ⟨1, 1, 1, -1, 0⟩,
  ⟨1, -1, 0, 1, -1⟩,
  ⟨0, -1, 0, 0, 0⟩,
  ⟨0, 0, 1, 0, 1⟩,
  ⟨0, -1, 0, 1, 0⟩,
  ⟨-1, 0, -1, 0, 0⟩,
  ⟨0, -1, 0, 1, 1⟩,
  ⟨0, 0, 1, 0, 0⟩,
  ⟨1, 1, 1, 1, 0⟩,
  ⟨1, 0, 0, -1, -1⟩,
  ⟨0, 1, -1, 1, -1⟩,
  ⟨-1, -1, -1, -1, 0⟩,
  ⟨1, -1, 0, 1, 0⟩,
  ⟨1, 1, -1, 1, -1⟩,
  ⟨-1, 1, 1, 1, -1⟩,
  ⟨0, 0, 1, 0, 1⟩,
  ⟨-1, -1, 0, 1, 1⟩,
  ⟨-1, 0, 1, -1, -1⟩,
  ⟨-1, 1, 1, 1, 1⟩,
  ⟨1, 0, 0, 0, 1⟩,
  ⟨0, -1, 0, -1, 1⟩,
  ⟨0, 1, 0, -1, 0⟩,
  ⟨-1, -1, 0, 1, -1⟩,
  ⟨-1, -1, 1, 1, -1⟩,
  ⟨-1, 1, 1, -1, -1⟩,
  ⟨0, 0, 0, 0, 0⟩,
  ⟨-1, -1, 0, 0, 1⟩,
  ⟨-1, 1, 1, -1, 0⟩,
  ⟨-1, 0, -1, 1, -1⟩,
  ⟨-1, -1, -1, 1, -1⟩,
  ⟨-1, -1, 0, 1, 0⟩,
  ⟨-1, 0, -1, -1, -1⟩,
  ⟨-1, 0, 1, 0, 0⟩,
  ⟨0, -1, 1, -1, -1⟩,
  ⟨1, 1, -1, -1, 1⟩,
  ⟨1, 0, 1, 1, 0⟩,
  ⟨1, 1, 0, 0, -1⟩,
  ⟨1, -1, 0, -1, 1⟩,
  ⟨-1, 0, 0, 1, -1⟩,
  ⟨-1, 0, 0, 0, -1⟩,
  ⟨1, 1, 1, 0, 1⟩,
  ⟨1, 1, 1, 0, -1⟩,
  ⟨1, 0, -1, -1, 0⟩]

def nibblePack : List Int → BitVec 32
  | [] => 0
  | x :: xs => (BitVec.ofInt 32 x &&& 15) ||| (nibblePack xs <<< 4)

def featureWord (x y : Int) : BitVec 32 :=
  nibblePack [x, y, x*x, y*y, x*y, x*x*y, x*y*y, 0]

def coefficientWord : BitVec 32 := nibblePack [0, -5, 0, 1, 1, 1, -2, 0]

def run (x y : Int) : Lane32 :=
  v_dot8_i32_iu4 { neg := 3 } coefficientWord (featureWord x y) 0

/-- All 64 hidden units have disappeared from this hardware expression.
Feature encoding is separate, input-dependent work; this is not a claim that the
whole program is one instruction or that it is optimal. Output is 2F. -/
theorem dot_replaces_network : ∀ x y : Fin 3,
    run (Int.ofNat x.val-1) (Int.ofNat y.val-1) =
      .ok (BitVec.ofInt 32 (2*network relu weights (Int.ofNat x.val-1) (Int.ofNat y.val-1))) := by
  decide +kernel

/-- Eight prepared bytes replace the whole observed function, including its
feature encoder. This output is a byte; sign extension is outside the contract. -/
def outputByte (x y : Fin 3) : BitVec 8 :=
  BitVec.ofInt 8 (2*network relu weights (Int.ofNat x.val-1) (Int.ofNat y.val-1))

theorem two_instructions_replace_network : ∀ x y : Fin 3,
    Kelana.TritObserver.run outputByte x y = .ok (outputByte x y) :=
  Kelana.TritObserver.observer_compilation outputByte (by decide +kernel)

end Kelana.ContractedToy
