-- Generated by research/discovery/joint-observer/discover.py.
import Kelana.PackedObserver

namespace Kelana.JointObserver

open Kelana.PackedObserver

def carrier (word : BitVec 32) : Int :=
  (((word * 27 + BitVec.ofInt 32 (-320)) >>> 6).setWidth 4).toInt

def atoms (x y z : Int) (i : Fin 19) : Int :=
  [    relu ((-1) * x + (-1) * y + (-1) * z) * x,
    relu ((-1) * x + (-1) * y + (-1) * z) * y,
    relu ((-1) * x + (-1) * y + (-1) * z) * z,
    relu ((-1) * x + (-1) * y + (0) * z) * x,
    relu ((-1) * x + (-1) * y + (0) * z) * y,
    relu ((-1) * x + (-1) * y + (1) * z) * x,
    relu ((-1) * x + (-1) * y + (1) * z) * z,
    relu ((-1) * x + (0) * y + (-1) * z) * x,
    relu ((-1) * x + (0) * y + (-1) * z) * y,
    relu ((-1) * x + (0) * y + (0) * z) * x,
    relu ((-1) * x + (0) * y + (1) * z) * y,
    relu ((-1) * x + (1) * y + (-1) * z) * x,
    relu ((-1) * x + (1) * y + (-1) * z) * y,
    relu ((-1) * x + (1) * y + (1) * z) * x,
    relu ((0) * x + (-1) * y + (-1) * z) * x,
    relu ((0) * x + (-1) * y + (-1) * z) * y,
    relu ((0) * x + (-1) * y + (1) * z) * x,
    relu ((0) * x + (1) * y + (-1) * z) * x,
    relu ((1) * x + (-1) * y + (-1) * z) * x][i.val]!

def coefficients (k : Fin 6) (i : Fin 19) : Int :=
  ([    [10, 1, 4, -2, 0, -9, 4, -8, -5, 11, 5, -7, 1, 5, -5, 0, 4, 2, 0],
    [64, -5, 64, 112, -24, -165, 64, -116, -29, 5, 125, -25, 1, 125, -35, 30, 64, 8, 0],
    [520, 571, 1024, 2488, -1320, -2829, 1024, -908, -245, -2299, 3125, -97, 1, 3125, -275, 750, 1024, 32, 0],
    [4504, 33475, 16384, 44392, -47544, -46965, 16384, 12844, -2189, -92515, 78125, -385, 1, 78125, -2315, 14070, 16384, 128, 0],
    [39880, 1206571, 262144, 745528, -1448520, -766749, 262144, 905572, -19685, -2875819, 1953125, -1537, 1, 1953125, -20195, 241950, 262144, 512, 0],
    [3, 1, -1, -2, -2, -2, 1, 0, -1, 0, 3, -2, 1, 3, 0, 0, 1, 1, 0]][k.val]!)[i.val]!

def source (k : Fin 6) (x y z : Int) : Int :=
  (List.ofFn fun i : Fin 19 => coefficients k i * atoms x y z i).sum

/-- A fixed 22-bit register table, addressed directly by the carried value. -/
def evenObserver (h : Int) : Int :=
  ((((BitVec.ofNat 32 3494231) >>> (2*(h+5)).toNat).setWidth 2).toNat : Int)

def observations (h : Int) (k : Fin 6) : Int :=
  match k.val with
  | 0 => h
  | 1 => h^3
  | 2 => h^5
  | 3 => h^7
  | 4 => h^9
  | _ => evenObserver h

/-- All six basis networks on every reachable input, checked by kernel reduction. -/
theorem source_observers : ∀ k : Fin 6, ∀ a b c : Fin 3,
    source k (trit a) (trit b) (trit c) = observations (carrier (packed a b c)) k := by
  decide

theorem even_observer_quadratic : ∀ a b c : Fin 3,
    evenObserver (carrier (packed a b c)) =
      trit b * trit b + trit b * trit c + trit c * trit c := by
  decide

def combine (v f : Fin 6 → Int) : Int :=
  v 0 * f 0 + v 1 * f 1 + v 2 * f 2 + v 3 * f 3 + v 4 * f 4 + v 5 * f 5

/-- Eleven carried states suffice for the entire six-parameter family. -/
def family (v : Fin 6 → Int) (x y z : Int) : Int :=
  combine v (fun k => source k x y z)

def consume (v : Fin 6 → Int) (h : Int) : Int :=
  h * (v 0 + h*h * (v 1 + h*h * (v 2 + h*h * (v 3 + h*h * v 4)))) +
  v 5 * evenObserver h

theorem horner (a0 a1 a2 a3 a4 h : Int) :
    a0*h + a1*h^3 + a2*h^5 + a3*h^7 + a4*h^9 =
    h*(a0+h*h*(a1+h*h*(a2+h*h*(a3+h*h*a4)))) := by
  simp only [Int.pow_succ, Int.pow_zero, Int.one_mul, Int.mul_add]
  ac_rfl

theorem combine_horner (v : Fin 6 → Int) (h : Int) :
    combine v (observations h) = consume v h :=
  congrArg (fun t => t + v 5 * evenObserver h) (horner (v 0) (v 1) (v 2) (v 3) (v 4) h)

/-- The parameters are arbitrary integers. Native signed24 range is a separate contract. -/
theorem whole_region (v : Fin 6 → Int) (a b c : Fin 3) :
    family v (trit a) (trit b) (trit c) = consume v (carrier (packed a b c)) :=
  (congrArg (combine v) (funext fun k => source_observers k a b c)).trans
    (combine_horner v (carrier (packed a b c)))

end Kelana.JointObserver
