import Kelana.ResourceBounds

/-! Generated by resource-bounds/core/export_lean.py.
Concrete dual arithmetic only. Feasible remains a semantic/service premise.
Zero-priced rows are omitted; remaining rows are scaled to integers.
No program semantics, schedule or native rate is inferred here. -/

namespace Kelana.ResourceCertificates
open Kelana.ResourceBounds

set_option maxRecDepth 8192
set_option maxHeartbeats 800000

-- separate-toggle optimum and strict domination; SHA256 bfd303d4150dd611acb9e1fdb0db61e013ed3a306758da9a8419b99d0e35ccf9
def case0Cuts : Obligations := ⟨[[1, 0], [0, 1]], [1, 1]⟩
def case0Machine : Machine := ⟨⟨"declared model ticks"⟩, [[1, 1]], [1], 0⟩
def case0Dual : Certificate := ⟨[1, 1], [1]⟩
theorem case0_checked :
    case0Dual.check case0Cuts case0Machine = true ∧
    case0Dual.work case0Cuts = 2 ∧
    case0Dual.service case0Machine = 1 := by decide
theorem case0_bound (e : Execution) (h : Feasible case0Cuts case0Machine e) :
    2 ≤ (e.ticks : Int) * 1 := by
  have bound := case0Dual.bound case0_checked.1 h
  rw [case0_checked.2.1, case0_checked.2.2] at bound
  exact bound

-- independent ports, latency 1; SHA256 d1d645863c30ddb0b3f7a07bc69273db71a9385240c571c65f8b28149866907d
def case1Cuts : Obligations := ⟨[[0, 1]], [1]⟩
def case1Machine : Machine := ⟨⟨"declared model ticks"⟩, [[0, 1]], [1], 0⟩
def case1Dual : Certificate := ⟨[1], [1]⟩
theorem case1_checked :
    case1Dual.check case1Cuts case1Machine = true ∧
    case1Dual.work case1Cuts = 1 ∧
    case1Dual.service case1Machine = 1 := by decide
theorem case1_bound (e : Execution) (h : Feasible case1Cuts case1Machine e) :
    1 ≤ (e.ticks : Int) * 1 := by
  have bound := case1Dual.bound case1_checked.1 h
  rw [case1_checked.2.1, case1_checked.2.2] at bound
  exact bound

-- independent ports, latency 4; SHA256 3b95ebb6b2f798dbe19b1513e36fb371b975ac81d3664b3b8ec0cd3d02686faf
def case2Cuts : Obligations := ⟨[[0, 1]], [1]⟩
def case2Machine : Machine := ⟨⟨"declared model ticks"⟩, [[0, 1]], [1], 0⟩
def case2Dual : Certificate := ⟨[1], [1]⟩
theorem case2_checked :
    case2Dual.check case2Cuts case2Machine = true ∧
    case2Dual.work case2Cuts = 1 ∧
    case2Dual.service case2Machine = 1 := by decide
theorem case2_bound (e : Execution) (h : Feasible case2Cuts case2Machine e) :
    1 ≤ (e.ticks : Int) * 1 := by
  have bound := case2Dual.bound case2_checked.1 h
  rw [case2_checked.2.1, case2_checked.2.2] at bound
  exact bound

-- xor-count-cut; SHA256 ab484e4b625aa0d5ba7afc04f2ea44dfd33dd965002e311c182a211235a03c2e
def case3Cuts : Obligations := ⟨[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [2]⟩
def case3Machine : Machine := ⟨⟨"declared model ticks"⟩, [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], [1], 0⟩
def case3Dual : Certificate := ⟨[1], [1]⟩
theorem case3_checked :
    case3Dual.check case3Cuts case3Machine = true ∧
    case3Dual.work case3Cuts = 2 ∧
    case3Dual.service case3Machine = 1 := by decide
theorem case3_bound (e : Execution) (h : Feasible case3Cuts case3Machine e) :
    2 ≤ (e.ticks : Int) * 1 := by
  have bound := case3Dual.bound case3_checked.1 h
  rw [case3_checked.2.1, case3_checked.2.2] at bound
  exact bound

-- relu-count-cut; SHA256 0eda6976aae1b37e0a9993e1677115e15abe596ea2786f9b6e376918ec1d17b1
def case4Cuts : Obligations := ⟨[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [2]⟩
def case4Machine : Machine := ⟨⟨"declared model ticks"⟩, [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], [1], 0⟩
def case4Dual : Certificate := ⟨[1], [1]⟩
theorem case4_checked :
    case4Dual.check case4Cuts case4Machine = true ∧
    case4Dual.work case4Cuts = 2 ∧
    case4Dual.service case4Machine = 1 := by decide
theorem case4_bound (e : Execution) (h : Feasible case4Cuts case4Machine e) :
    2 ≤ (e.ticks : Int) * 1 := by
  have bound := case4Dual.bound case4_checked.1 h
  rw [case4_checked.2.1, case4_checked.2.2] at bound
  exact bound

end Kelana.ResourceCertificates
