import Std

namespace Kelana.ValueErrorFeedback

/-- Sum over the finite prefix `0, …, n-1`. -/
def prefixSum (f : Nat → Rat) : Nat → Rat
  | 0 => 0
  | n + 1 => prefixSum f n + f n

theorem prefixSum_congr {f g : Nat → Rat} (h : ∀ i, f i = g i) (n : Nat) :
    prefixSum f n = prefixSum g n := by
  induction n with
  | zero => rfl
  | succ n ih => simp only [prefixSum, ih, h n]

/-- Decoded minus source value. `eta` names the defect of an implemented
update from its stated rational recurrence; no floating-point behavior is
assumed. -/
def valueError (value decode : Nat → Rat) (i : Nat) : Rat :=
  decode i - value i

/-- The causal update makes the current value error a residual difference plus
its update defect. -/
theorem error_from_recurrence (r value decode eta : Nat → Rat)
    (h : ∀ i, r (i + 1) = r i + value i - decode i + eta i) (i : Nat) :
    valueError value decode i = r i - r (i + 1) + eta i := by
  unfold valueError
  have hi := h i
  grind +ring

/-- Finite summation by parts: residual differences control the boundary
and the variation of the observer's weights, while update defects remain
explicit. This applies also to the empty prefix. -/
theorem weighted_residual_identity (p r eta : Nat → Rat) (n : Nat) :
    prefixSum (fun i => p i * (r i - r (i + 1) + eta i)) n =
      p 0 * r 0 - p n * r n +
      prefixSum (fun i => (p (i + 1) - p i) * r (i + 1)) n +
      prefixSum (fun i => p i * eta i) n := by
  induction n with
  | zero => simp only [prefixSum]
            grind +ring
  | succ n ih =>
    simp only [prefixSum]
    rw [ih]
    grind +ring

/-- Exposing the carried residual at the probability of its last encoded
source token removes the boundary term, not the interior weight variation.
There are `n+1` encoded tokens here; the empty case needs no correction. -/
theorem source_visible_residual (p r eta : Nat → Rat) (n : Nat) :
    prefixSum (fun i => p i * (r i - r (i + 1) + eta i)) (n+1) +
      p n * r (n+1) =
    p 0 * r 0 +
      prefixSum (fun i => (p (i+1) - p i) * r (i+1)) n +
      prefixSum (fun i => p i * eta i) (n+1) := by
  rw [weighted_residual_identity]
  simp only [prefixSum]
  grind +ring

/-- Under uniform weights, the interior variation vanishes. -/
theorem uniform_weight (c : Rat) (r eta : Nat → Rat) (n : Nat)
    (h0 : r 0 = 0) :
    prefixSum (fun i => c * (r i - r (i + 1) + eta i)) n =
      -(c * r n) + prefixSum (fun i => c * eta i) n := by
  have h := weighted_residual_identity (fun _ => c) r eta n
  have hz (n : Nat) : prefixSum (fun i => (c - c) * r (i + 1)) n = 0 := by
    induction n with
    | zero => rfl
    | succ n ih =>
      simp only [prefixSum]
      rw [ih]
      grind +ring
  rw [hz, h0] at h
  grind +ring

/-- Apply the observer identity to the exact recurrence, using decoded
minus source value as the error sign convention. -/
theorem recurrence_weighted_error (p r value decode eta : Nat → Rat) (n : Nat)
    (h : ∀ i, r (i + 1) = r i + value i - decode i + eta i) :
    prefixSum (fun i => p i * valueError value decode i) n =
      p 0 * r 0 - p n * r n +
      prefixSum (fun i => (p (i + 1) - p i) * r (i + 1)) n +
      prefixSum (fun i => p i * eta i) n := by
  rw [← weighted_residual_identity]
  apply prefixSum_congr
  intro i
  rw [error_from_recurrence r value decode eta h i]

/-- The uniform-weight consequence for errors generated by the recurrence.
A small final residual alone says nothing about the accumulated defects. -/
theorem recurrence_uniform_weight (c : Rat) (r value decode eta : Nat → Rat)
    (n : Nat) (h0 : r 0 = 0)
    (h : ∀ i, r (i + 1) = r i + value i - decode i + eta i) :
    prefixSum (fun i => c * valueError value decode i) n =
      -(c * r n) + prefixSum (fun i => c * eta i) n := by
  rw [← uniform_weight c r eta n h0]
  apply prefixSum_congr
  intro i
  rw [error_from_recurrence r value decode eta h i]

/-- The changed reader consumes the actual carried residual, so in the
uniform-weight case only implemented update defects remain. -/
theorem recurrence_uniform_visible (c : Rat) (r value decode eta : Nat → Rat)
    (n : Nat) (h0 : r 0 = 0)
    (h : ∀ i, r (i + 1) = r i + value i - decode i + eta i) :
    prefixSum (fun i => c * valueError value decode i) n + c * r n =
      prefixSum (fun i => c * eta i) n := by
  rw [recurrence_uniform_weight c r value decode eta n h0 h]
  grind +ring

/-- A fixed rational linear coordinate commutes with the finite observer sum.
This does not assert anything about adaptive weights or floating arithmetic. -/
theorem coordinate_pushforward (a : Rat) (p e : Nat → Rat) (n : Nat) :
    prefixSum (fun i => p i * (a * e i)) n =
      a * prefixSum (fun i => p i * e i) n := by
  induction n with
  | zero => simp only [prefixSum]; grind +ring
  | succ n ih =>
    simp only [prefixSum]
    rw [ih]
    grind +ring

/-- Zero aggregate error can still be visible to a selective two-token
observer: the signed errors cancel, but only the first token is read. -/
theorem selective_two_token_witness :
    prefixSum (fun i => if i = 0 then (1 : Rat) else -1) 2 = 0 ∧
    prefixSum (fun i =>
      (if i = 0 then (1 : Rat) else 0) *
        (if i = 0 then (1 : Rat) else -1)) 2 = 1 := by
  constructor <;> (simp only [prefixSum]; grind +ring)

/-- A symmetric rational interval, without assuming any floating format. -/
def Within (x radius : Rat) : Prop := -radius ≤ x ∧ x ≤ radius

/-- An ideal clipped quantizer: endpoints outside the interval and an interior
error radius. A nearest uniform grid supplies half its spacing as `gap`. -/
def Clipped (lo hi gap target decoded : Rat) : Prop :=
  (target < lo → decoded = lo) ∧
  (hi < target → decoded = hi) ∧
  (lo ≤ target → target ≤ hi → Within (target - decoded) gap)

/-- Changing ranges do not by themselves destabilize ideal first-order
feedback when each interval contains its own source and its gap is bounded. -/
theorem clipped_residual_bound (lo hi gap v r decoded R B : Rat)
    (hsource : lo ≤ v ∧ v ≤ hi) (hr : Within r R)
    (hR : R ≤ B) (hgap : gap ≤ B)
    (hq : Clipped lo hi gap (v+r) decoded) :
    Within (v+r-decoded) B := by
  unfold Clipped at hq
  unfold Within at *
  by_cases hl : v+r < lo
  · have hd := hq.1 hl
    grind
  · by_cases hh : hi < v+r
    · have hd := hq.2.1 hh
      grind
    · have ha : lo ≤ v+r := by grind
      have hb : v+r ≤ hi := by grind
      have hd := hq.2.2 ha hb
      grind

/-- Separate perturbations of target formation, ideal reconstruction and
update arithmetic. The latter two errors can each enlarge the residual. -/
theorem perturbed_clipped_bound
    (lo hi gap v r ideal beta xi gamma R U D G B : Rat)
    (hsource : lo ≤ v ∧ v ≤ hi) (hr : Within r R)
    (hbeta : Within beta U) (hxi : Within xi D) (hgamma : Within gamma G)
    (hR : R+U ≤ B) (hgap : gap ≤ B)
    (hq : Clipped lo hi gap (v+r+beta) ideal) :
    Within (v+r+beta-(ideal+xi)+gamma) (B+D+G) := by
  have ht : Within (r+beta) (R+U) := by
    unfold Within at *
    grind
  have hq' : Clipped lo hi gap (v+(r+beta)) ideal := by
    simpa only [Rat.add_assoc] using hq
  have h := clipped_residual_bound lo hi gap v (r+beta) ideal (R+U) B
    hsource ht hR hgap hq'
  unfold Within at *
  grind

private theorem prefix_nonneg (f : Nat → Rat) (hf : ∀ i, 0 ≤ f i) (n : Nat) :
    0 ≤ prefixSum f n := by
  induction n with
  | zero => simp [prefixSum]
  | succ n ih =>
    have hn := hf n
    simp only [prefixSum]
    grind

/-- A complete varying-grid stability budget. With exact target, decoder and
update arithmetic all defect bounds vanish, leaving a uniform gap bound H.
This theorem does not assert that a particular rounded program meets it. -/
theorem varying_grid_budget
    (lo hi gap v r ideal beta xi gamma U D G : Nat → Rat) (H : Rat)
    (h0 : Within (r 0) H)
    (hsource : ∀ i, lo i ≤ v i ∧ v i ≤ hi i)
    (hgap : ∀ i, gap i ≤ H)
    (hU : ∀ i, 0 ≤ U i) (hD : ∀ i, 0 ≤ D i) (hG : ∀ i, 0 ≤ G i)
    (hbeta : ∀ i, Within (beta i) (U i))
    (hxi : ∀ i, Within (xi i) (D i))
    (hgamma : ∀ i, Within (gamma i) (G i))
    (hq : ∀ i, Clipped (lo i) (hi i) (gap i) (v i+r i+beta i) (ideal i))
    (hupdate : ∀ i, r (i+1) = v i+r i+beta i-(ideal i+xi i)+gamma i)
    (n : Nat) :
    Within (r n) (H+prefixSum (fun i => U i+D i+G i) n) := by
  induction n with
  | zero => simpa only [prefixSum, Rat.add_zero] using h0
  | succ n ih =>
    let E := fun i => U i+D i+G i
    have hE : ∀ i, 0 ≤ E i := by
      intro i
      have h1 := hU i
      have h2 := hD i
      have h3 := hG i
      dsimp [E]
      grind
    have hp := prefix_nonneg E hE n
    have hu := hU n
    have hg := hgap n
    have hg' : gap n ≤ H+prefixSum E n+U n := by grind
    have h := perturbed_clipped_bound (lo n) (hi n) (gap n) (v n) (r n)
      (ideal n) (beta n) (xi n) (gamma n) (H+prefixSum E n)
      (U n) (D n) (G n) (H+prefixSum E n+U n)
      (hsource n) ih (hbeta n) (hxi n) (hgamma n) (by exact Rat.le_refl) hg' (hq n)
    rw [hupdate n]
    simp only [prefixSum]
    unfold Within at *
    dsimp [E] at h
    grind

/-- Four-token exact uniform-grid example, not a source-model witness. -/
def witnessResidual (i : Nat) : Rat :=
  if i = 1 then 1/12 else if i = 2 then 1/6 else if i = 3 then -1/12 else 0

def witnessCode (i : Nat) : Nat := if i = 2 then 1 else 0

def witnessDecoded (i : Nat) : Rat := (witnessCode i : Rat)/3

def witnessProbability (i : Nat) : Rat := if i = 2 then 3/4 else 1/12

/-- Every chosen code minimizes exact squared distance to the four-level grid;
the half-step tie at the second token chooses the even code zero. -/
theorem witness_grid_and_recurrence :
    (∀ i : Fin 4, witnessCode i.val < 4 ∧
      witnessResidual (i.val+1) = 1/12+witnessResidual i.val-witnessDecoded i.val ∧
      ∀ j : Fin 4,
        (1/12+witnessResidual i.val-witnessDecoded i.val)^2 ≤
          (1/12+witnessResidual i.val-(j.val : Rat)/3)^2) ∧
    (∀ i : Fin 5, Within (witnessResidual i.val) (1/6)) ∧
    witnessResidual 0 = 0 ∧ witnessResidual 4 = 0 := by
  unfold Within
  decide +kernel

/-- Strictly positive, normalized selective weights quadruple feedback's
squared error versus the original nearest-grid codes, despite zero uniform
feedback error and a stable residual throughout. -/
theorem witness_stable_but_selective_worse :
    (∀ i : Fin 4, 0 < witnessProbability i.val) ∧
    prefixSum witnessProbability 4 = 1 ∧
    prefixSum (fun i => (1/4 : Rat)*(witnessDecoded i-1/12)) 4 = 0 ∧
    prefixSum (fun i => witnessProbability i*(witnessDecoded i-1/12)) 4 = 1/6 ∧
    prefixSum (fun i => witnessProbability i*(0-1/12)) 4 = -1/12 ∧
    ((1/6 : Rat)^2 = 4*((-1/12 : Rat)^2)) := by
  decide +kernel

end Kelana.ValueErrorFeedback
