#!/usr/bin/env python3
"""Reproduce the bounded search and export the selected exact family."""
import json
import sys
from itertools import product
from pathlib import Path

import sympy as sp

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "observer-search"))
from inverse_labels import STATES, CODES, ZERO, candidates, source_basis
from joint import (SourceSpace, polynomial_features, label_features,
                   separates_all_coordinates, collision_witness)


def signed(value, width):
    value &= (1 << width) - 1
    return value - (1 << width) if value >= (1 << (width-1)) else value


def producer(q):
    word = ((q & 0xffffff) * 27 - 320) & 0xffffffff
    return signed(word >> 6, 4)


def native_consumer(h, coefficients):
    """Bit-accurate scalar model of signed24 multiply/MAD, not a native run."""
    def mul(a, b):
        return signed(signed(a, 24) * signed(b, 24), 32)
    def mad(a, b, c):
        return signed(signed(a, 24) * signed(b, 24) + signed(c, 32), 32)
    if len(coefficients) not in (5, 6):
        raise ValueError("five odd coefficients, optionally one even coefficient")
    z = mul(h, h)
    p = coefficients[4]
    for c in reversed(coefficients[:4]):
        p = mad(z, p, c)
    output = mul(h, p)
    if len(coefficients) == 6:
        offset = signed((h << 1) + 10, 32)
        even = (0x355157 >> (offset & 31)) & 3
        output = mad(even, coefficients[5], output)
    return output


def matrix_json(m):
    return [[str(x) for x in m.row(i)] for i in range(m.rows)]


def lean_export(atoms, coefficients):
    # One generated source basis, checked independently on the full domain by Lean.
    atoms_lean = []
    for g, j in atoms:
        gate = " + ".join(f"({a}) * {x}" for a, x in zip(g, ("x", "y", "z")))
        atoms_lean.append(f"    relu ({gate}) * {('x', 'y', 'z')[j]}")
    rows = ["    [" + ", ".join(str(coefficients[i, j]) for i in range(len(atoms))) + "]"
            for j in range(6)]
    text = '''-- Generated by research/discovery/joint-observer/discover.py.
import Kelana.PackedObserver

namespace Kelana.JointObserver

open Kelana.PackedObserver

def carrier (word : BitVec 32) : Int :=
  (((word * 27 + BitVec.ofInt 32 (-320)) >>> 6).setWidth 4).toInt

def atoms (x y z : Int) (i : Fin 19) : Int :=
  [ATOMS][i.val]!

def coefficients (k : Fin 6) (i : Fin 19) : Int :=
  ([COEFFICIENTS][k.val]!)[i.val]!

def source (k : Fin 6) (x y z : Int) : Int :=
  (List.ofFn fun i : Fin 19 => coefficients k i * atoms x y z i).sum

/-- A fixed 22-bit register table, addressed directly by the carried value. -/
def evenObserver (h : Int) : Int :=
  ((((BitVec.ofNat 32 3494231) >>> (2*(h+5)).toNat).setWidth 2).toNat : Int)

def observations (h : Int) (k : Fin 6) : Int :=
  match k.val with
  | 0 => h
  | 1 => h^3
  | 2 => h^5
  | 3 => h^7
  | 4 => h^9
  | _ => evenObserver h

/-- All six basis networks on every reachable input, checked by kernel reduction. -/
theorem source_observers : ∀ k : Fin 6, ∀ a b c : Fin 3,
    source k (trit a) (trit b) (trit c) = observations (carrier (packed a b c)) k := by
  decide

theorem even_observer_quadratic : ∀ a b c : Fin 3,
    evenObserver (carrier (packed a b c)) =
      trit b * trit b + trit b * trit c + trit c * trit c := by
  decide

def combine (v f : Fin 6 → Int) : Int :=
  v 0 * f 0 + v 1 * f 1 + v 2 * f 2 + v 3 * f 3 + v 4 * f 4 + v 5 * f 5

/-- Eleven carried states suffice for the entire six-parameter family. -/
def family (v : Fin 6 → Int) (x y z : Int) : Int :=
  combine v (fun k => source k x y z)

def consume (v : Fin 6 → Int) (h : Int) : Int :=
  h * (v 0 + h*h * (v 1 + h*h * (v 2 + h*h * (v 3 + h*h * v 4)))) +
  v 5 * evenObserver h

theorem horner (a0 a1 a2 a3 a4 h : Int) :
    a0*h + a1*h^3 + a2*h^5 + a3*h^7 + a4*h^9 =
    h*(a0+h*h*(a1+h*h*(a2+h*h*(a3+h*h*a4)))) := by
  simp only [Int.pow_succ, Int.pow_zero, Int.one_mul, Int.mul_add]
  ac_rfl

theorem combine_horner (v : Fin 6 → Int) (h : Int) :
    combine v (observations h) = consume v h :=
  congrArg (fun t => t + v 5 * evenObserver h) (horner (v 0) (v 1) (v 2) (v 3) (v 4) h)

/-- The parameters are arbitrary integers. Native signed24 range is a separate contract. -/
theorem whole_region (v : Fin 6 → Int) (a b c : Fin 3) :
    family v (trit a) (trit b) (trit c) = consume v (carrier (packed a b c)) :=
  (congrArg (combine v) (funext fun k => source_observers k a b c)).trans
    (combine_horner v (carrier (packed a b c)))

end Kelana.JointObserver
'''
    text = text.replace("ATOMS", ",\n".join(atoms_lean)).replace("COEFFICIENTS", ",\n".join(rows))
    (HERE.parents[2] / "Kelana" / "JointObserver.lean").write_text(text)


def run():
    atoms, a = source_basis()
    space = SourceSpace(a)
    records = []
    examined = eligible = 0
    for spec, raw in candidates():
        examined += 1
        h = tuple(v - raw[ZERO] for v in raw)
        if not 3 <= len(set(h)) < len(STATES) or not separates_all_coordinates(STATES, h):
            continue
        eligible += 1
        family = space.intersect(polynomial_features(h, (1, 2, 3)))
        if family.dimension >= 2:
            records.append({"producer": spec, "centering": raw[ZERO],
                            "states": len(set(h)), "function_dimension": family.dimension,
                            "coefficient_nullity": family.coefficient_nullity,
                            "consumer_coefficients": matrix_json(family.consumer_coefficients)})
    h = tuple(producer(q) for q in CODES)
    assert h == tuple(27*q//64-5 for q in CODES)
    even = tuple(int(v != 0) + 2*int(abs(v) == 5) for v in h)
    assert even == tuple(y*y+y*z+z*z for x, y, z in STATES)
    assert all(((0x355157 >> (2*(v+5))) & 3) == e for v, e in zip(h, even))
    features = polynomial_features(h, (1, 3, 5, 7, 9)).row_join(sp.Matrix(even))
    family = space.intersect(features)
    assert family.dimension == 6
    assert family.consumer_coefficients == sp.eye(6)
    assert all(c.q == 1 for c in family.source_coefficients)
    full_labels = space.intersect(label_features(h))
    assert full_labels.dimension == family.dimension
    checks = 0
    for c in product((-7, 0, 7), repeat=6):
        for v in range(-5, 6):
            expected = sum(c[i]*v**(2*i+1) for i in range(5)) + c[5]*(int(v != 0)+2*int(abs(v)==5))
            assert native_consumer(v, c) == expected
            checks += 1
    hidden_states = [tuple(a.row(i)) for i in range(a.rows)]
    obstruction = collision_witness(h, [int(v) for v in a[:, 0]])
    obstruction["first_input"] = STATES[obstruction["first"]]
    obstruction["second_input"] = STATES[obstruction["second"]]
    lean_export(atoms, family.source_coefficients)
    return {
        "scope": "Constructed three-trit ReLU-gated families. No trained-model match or speed measurement.",
        "search": {"generated": examined, "eligible": eligible, "consumer_powers": [1, 2, 3],
                   "complete": True, "matching_numeric_maps": records,
                   "deduplication": "none; numeric labels retained"},
        "selected": {"formula": "h(q)=signed_bfe32(27*q-320,6,4)",
                     "input": "q=(x+1)+3*(y+1)+9*(z+1), supplied already packed",
                     "inputs": STATES, "q": CODES, "h": h,
                     "hidden_vector_states": len(set(hidden_states)), "carrier_states": len(set(h)),
                     "consumer": "h*(a0+h*h*(a1+h*h*(a2+h*h*(a3+h*h*a4)))) + a5*BFE(0x355157,2*h+10,2)",
                     "family_dimension": family.dimension, "arbitrary_label_intersection_dimension": full_labels.dimension,
                     "extra_even_function": "[h!=0]+2*[abs(h)==5] = y*y+y*z+z*z",
                     "source_atoms": [{"gate": g, "up_coordinate": j} for g, j in atoms],
                     "source_coefficients": matrix_json(family.source_coefficients),
                     "unpreserved_source_atom": obstruction,
                     "native_contract": {"coefficient_range": [-7, 7], "max_square": 25,
                                         "max_horner_operand": 7*sum(25**i for i in range(5)),
                                         "max_output": 35*sum(25**i for i in range(5))+21,
                                         "scalar_emulator_cases": checks,
                                         "producer_data_instructions": 2, "odd_consumer_data_instructions": 6,
                                         "full_consumer_data_instructions": 9,
                                         "excludes": "input packing, coefficient setup, memory operations, scheduling and endpoint stores"}}
    }


if __name__ == "__main__":
    result = run()
    (HERE / "results.json").write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps({"search_matches": len(result["search"]["matching_numeric_maps"]),
                      "selected": {k: v for k, v in result["selected"].items()
                                   if k not in {"inputs", "q", "h", "source_atoms", "source_coefficients"}}}, indent=2))
