#!/usr/bin/env python3
"""Rebuild the range tables from retained per-region measurements."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
paths = sorted((HERE/"trained-results").glob("layer*-anchor*.json"))
records = [json.loads(p.read_text()) for p in paths]
if len(records) != 4:
    raise SystemExit("expected both anchors of both layers")


def span(cases, get):
    values = [100*get(c) for c in cases]
    low, high = min(values), max(values)
    return f"{low:.3g} to {high:.3g}%" if high < 0.01 else f"{low:.3f} to {high:.3f}%"


def bound(c, m):
    return next(x["relative_rms_lower_bound"] for x in c["any_carrier_capacity_lower_bounds"]
                if x["capacity"] == m)


lines = ["# Fixed trained-region results", "",
         "Generated by `summarize_trained.py`. Ranges cover twelve regions per hidden quantizer setting.",
         "All errors below use output variation over the 27-state cube as denominator, except the explicitly marked full-update column.", "",
         "| Hidden quantizer | Selected family error | Free decoder on same carrier | Best orientation | Family error / full update |",
         "|---|---:|---:|---:|---:|"]
for levels, name in ((0, "None"), (127, "A8"), (7, "A4")):
    cases = [c for r in records for c in r["cases"] if c["hidden_quantizer_levels"] == levels]
    columns = [span(cases, lambda c: c["selected_carrier"]["family_rel_rms"]),
               span(cases, lambda c: c["selected_carrier"]["arbitrary_decoder_rel_rms"]),
               span(cases, lambda c: c["best_orientation"]["family_rel_rms"]),
               span(cases, lambda c: c["selected_carrier"]["family_rel_rms_over_full_update"])]
    lines.append("| "+" | ".join([name]+columns)+" |")
lines += ["", "The next bounds allow any encoder and any decoder on these computed vector tables.", "",
          "| Hidden quantizer | Any 11-state carrier, lower bound | Any 16-state carrier, lower bound | Any 26-state carrier, lower bound | Best tested ≤16-state partition, achieved |",
          "|---|---:|---:|---:|---:|"]
for levels, name in ((0, "None"), (127, "A8"), (7, "A4")):
    cases = [c for r in records for c in r["cases"] if c["hidden_quantizer_levels"] == levels]
    columns = [span(cases, lambda c, m=m: bound(c, m)) for m in (11, 16, 26)]
    columns += [span(cases, lambda c: c["grammar_fiber_frontier"][-1]["best_arbitrary_decoder_rel_rms"])]
    lines.append("| "+" | ".join([name]+columns)+" |")
lines += ["", "| Hidden quantizer | Linear fit | Quadratic fit | Cubic fit |",
          "|---|---:|---:|---:|"]
for levels, name in ((0, "None"), (127, "A8"), (7, "A4")):
    cases = [c for r in records for c in r["cases"] if c["hidden_quantizer_levels"] == levels]
    lines.append("| "+" | ".join([name]+[span(cases, lambda c, d=d: c["polynomial_controls"][d]["rel_rms"])
                                              for d in ("1", "2", "3")])+" |")
errors = [c["zero_perturbation_vs_captured_update_rel_rms"] for r in records for c in r["cases"]
          if "zero_perturbation_vs_captured_update_rel_rms" in c]
lines += ["", f"CPU A8 zero-perturbation check against captured engine update: relative RMS {min(errors):.3e} to {max(errors):.3e}.",
          "Every computed 27-state output table has 27 distinct vectors.", "",
          "These are per-case oracle fits, not timed implementations. The anchors and input groups are prescribed; the fitted coefficients and best maps may change with them.",
          "", "## Records", ""]
lines += [f"- [{p.name}]({p.name})" for p in paths]
(HERE/"trained-results/summary.md").write_text("\n".join(lines)+"\n")
print(HERE/"trained-results/summary.md")
