#!/usr/bin/env python3
"""Export a rational polynomial identity to a kernel-checked Lean certificate.

The Python canonicalizer proposes equality. Lean recomputes the normal forms
from both ORIGINAL expression trees, so the proposal isn't a trusted premise.
"""
import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / 'ternary-algebra'))
from ternary_algebra import Poly, difference_witness


def rational(value):
    if isinstance(value, bool) or not isinstance(value, (str, int)):
        raise ValueError('literals must be integers or exact rational strings, not JSON floats')
    return Fraction(value)


def expression(tree, arity, budget, depth=0):
    budget[0] -= 1
    if budget[0] < 0 or depth > 64:
        raise ValueError('expression exceeds 2048 nodes or depth 64')
    if not isinstance(tree, list) or not tree:
        raise ValueError('expected [lit,value], [var,index], [add,a,b] or [mul,a,b]')
    op = tree[0]
    if op == 'lit' and len(tree) == 2:
        q = rational(tree[1])
        literal = str(q.numerator) if q.denominator == 1 else f'({q.numerator} / {q.denominator})'
        return Poly.constant(q), f'(.lit ({literal} : Rat))'
    if op == 'var' and len(tree) == 2:
        i = tree[1]
        if isinstance(i, bool) or not isinstance(i, int) or not 0 <= i < arity:
            raise ValueError('variable index outside declared arity')
        return Poly.variable(f'x{i}'), f'(.var ⟨{i}, by decide⟩)'
    if op in ('add', 'mul') and len(tree) == 3:
        a, la = expression(tree[1], arity, budget, depth + 1)
        b, lb = expression(tree[2], arity, budget, depth + 1)
        return (a + b if op == 'add' else a * b), f'(.{"plus" if op == "add" else "times"} {la} {lb})'
    raise ValueError(f'invalid expression node: {tree[:1]}')


def export(spec_path, out):
    raw = spec_path.read_bytes()
    spec = json.loads(raw)
    n = spec['arity']
    if isinstance(n, bool) or not isinstance(n, int) or not 0 <= n <= 6:
        raise ValueError('certificate exporter supports arity 0 through 6')
    budget = [2048]
    a, left = expression(spec['lhs'], n, budget)
    b, right = expression(spec['rhs'], n, budget)
    witness = difference_witness(a, b, [f'x{i}' for i in range(n)])
    if witness is not None:
        return {'equal': False, 'input': witness,
                'lhs': str(a.evaluate(witness)), 'rhs': str(b.evaluate(witness))}
    fingerprint = hashlib.sha256(raw).hexdigest()
    namespace = 'Map_' + fingerprint[:16]
    source = f'''import Kelana.TernaryAlgebra

-- Input SHA-256: {fingerprint}
-- Generated by research/discovery/certificates/export_lean.py.
-- Both original expressions are evaluated in exact rational arithmetic.
namespace {namespace}
open Kelana.TernaryAlgebra

def lhs : Expr Rat {n} := {left}
def rhs : Expr Rat {n} := {right}

theorem normal_forms_equal : lhs.normalize = rhs.normalize := by decide +kernel

theorem discovered_identity (x : Fin {n} → Rat) (hx : CubicGrid x) :
    lhs.eval x = rhs.eval x :=
  equivalent_of_normal_equal lhs rhs normal_forms_equal x hx

#print axioms discovered_identity
end {namespace}
'''
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source)
    return {'equal': True, 'certificate': str(out), 'input_sha256': fingerprint,
            'certificate_sha256': hashlib.sha256(source.encode()).hexdigest(),
            'profile': a.profile(), 'nodes': 2048 - budget[0],
            'proof_status': 'exported; run lake env lean on the certificate to check it'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('spec', type=Path)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    report = export(args.spec, args.out)
    print(json.dumps(report, indent=2))
    return 0 if report['equal'] else 1


if __name__ == '__main__':
    raise SystemExit(main())
