#!/usr/bin/env python3
"""Read the pinned AMD specification; emit its full index or selected records."""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import signal
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "sources/amdgpu_isa_rdna3_5.xml"


def record(element):
    result = dict(element.attrib)
    text = (element.text or "").strip()
    if not len(element):
        return {**result, "value": text} if result else text
    if text:
        result["text"] = text
    for child in element:
        result.setdefault(child.tag, []).append(record(child))
    return result


def description(node):
    return " ".join("".join(node.find("Description").itertext()).split())


def signature(encoding):
    inputs, outputs = [], []
    for operand in encoding.findall("Operands/Operand"):
        name = operand.findtext("FieldName") or operand.findtext("OperandType")
        fmt = operand.findtext("DataFormatName").removeprefix("FMT_")
        width = operand.findtext("OperandSize")
        implicit = "*" if operand.get("IsImplicit") == "true" else ""
        item = f"{name}{implicit}:{fmt}[{width}]"
        if operand.get("Input") == "true":
            inputs.append(item)
        if operand.get("Output") == "true":
            outputs.append(item)
    return ", ".join(inputs) + " → " + ", ".join(outputs)


def validate(isa):
    sections = {
        "Instructions": "InstructionName", "Encodings": "EncodingName",
        "DataFormats": "DataFormatName", "OperandTypes": "OperandTypeName",
    }
    names = {}
    for section, key in sections.items():
        values = [node.findtext(key) for node in isa.find(section)]
        if None in values or len(values) != len(set(values)):
            raise ValueError(f"Missing or repeated names in {section}")
        names[section] = set(values)
    for insn in isa.find("Instructions"):
        for encoding in insn.findall("InstructionEncodings/InstructionEncoding"):
            if encoding.findtext("EncodingName") not in names["Encodings"]:
                raise ValueError(f"Unknown encoding in {insn.findtext('InstructionName')}")
            for operand in encoding.findall("Operands/Operand"):
                for key, section in [("DataFormatName", "DataFormats"), ("OperandType", "OperandTypes")]:
                    if operand.findtext(key) not in names[section]:
                        raise ValueError(f"Unknown {key} in {insn.findtext('InstructionName')}")


def index(root):
    isa = root.find("ISA")
    instructions = list(isa.find("Instructions"))
    counts = Counter(i.findtext("FunctionalGroup/Name") for i in instructions)
    lines = ["# AMD RDNA 3.5 instruction index", "",
             "Generated by `python3 catalogue.py index` from the pinned AMD XML. Do not edit.", "",
             f"{len(instructions)} canonical instruction names; "
             f"{sum(len(i.find('InstructionEncodings')) for i in instructions)} encoding records. "
             "Encoding records include literal and operand variants, not just distinct opcodes.", "",
             "Types are AMD data-format names. Brackets give the XML operand width in bits. "
             "`*` marks an implicit operand. WMMA widths describe lane fragments, not whole matrices. "
             "These signatures do not enumerate every architectural effect; EXEC, MODE and memory ordering still apply.", "",
             "Use `python3 catalogue.py instruction NAME` for all encodings, flags, aliases and operand records. "
             "Use `format`, `operand` or `encoding` to expand their definitions.", ""]
    for group in sorted(counts):
        lines += [f"## {group}: {counts[group]}", ""]
        for insn in instructions:
            if insn.findtext("FunctionalGroup/Name") != group:
                continue
            name = insn.findtext("InstructionName")
            lines += [f"### {name}", "", description(insn), ""]
            aliases = [a.text for a in insn.findall("AliasedInstructionNames/InstructionName")]
            if aliases:
                lines += ["Aliases: " + ", ".join(f"`{a}`" for a in aliases) + ".", ""]
            signatures = dict.fromkeys(signature(e) for e in insn.find("InstructionEncodings"))
            lines += [f"- `{s}`" for s in signatures]
            lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kind", choices=["index", "summary", "instruction", "format", "operand", "encoding"])
    parser.add_argument("pattern", nargs="?", default=".*", help="case-insensitive regular expression")
    args = parser.parse_args()
    root = ET.parse(SOURCE).getroot()
    isa = root.find("ISA")
    validate(isa)
    if args.kind == "index":
        print(index(root))
        return
    if args.kind == "summary":
        instructions = list(isa.find("Instructions"))
        result = {
            "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
            "document": record(root.find("Document")),
            "architecture": record(isa.find("Architecture")),
            "counts": {section.tag: len(section) for section in isa if section.tag != "Architecture"},
            "instruction_encoding_records": sum(len(i.find("InstructionEncodings")) for i in instructions),
            "groups": dict(sorted(Counter(i.findtext("FunctionalGroup/Name") for i in instructions).items())),
        }
    else:
        section, key = {
            "instruction": ("Instructions", "InstructionName"),
            "format": ("DataFormats", "DataFormatName"),
            "operand": ("OperandTypes", "OperandTypeName"),
            "encoding": ("Encodings", "EncodingName"),
        }[args.kind]
        pattern = re.compile(args.pattern, re.IGNORECASE)
        matches = [node for node in isa.find(section)
                   if pattern.search(node.findtext(key))
                   or (args.kind == "instruction" and any(pattern.search(a.text) for a in node.findall("AliasedInstructionNames/InstructionName")))]
        if not matches:
            parser.exit(1, f"No {args.kind} matches {args.pattern!r}\n")
        result = [record(node) for node in matches]
    json.dump(result, sys.stdout, indent=2, ensure_ascii=False)
    print()


if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    main()
