#!/usr/bin/env python3
"""Six-bit labels into a codebook generated by six learned response directions."""
import json
from pathlib import Path

import numpy as np
import study

HERE = Path(__file__).resolve().parent
L = 8
B = 6


def fit(x, iterations=12):
    # Coordinate descent over independent binary labels and least-squares
    # directions. Each step decreases the full-vector squared error until the
    # final quantization; optimality is only conditional on the other variables.
    mean = x.mean(axis=0)
    residual = x-mean
    directions = []
    for _ in range(B):
        _, _, vh = np.linalg.svd(residual, full_matrices=False)
        direction = vh[0]
        signs = np.where(residual@direction >= 0, 1., -1.)
        basis = (residual*signs[:,None]).mean(axis=0)
        directions.append(basis)
        residual -= signs[:,None]*basis
    basis = np.stack(directions)
    signs = np.sign((x-mean)@basis.T)
    signs[signs==0] = 1
    for _ in range(iterations):
        for j in range(B):
            remainder = x-mean-signs@basis+signs[:,j,None]*basis[j]
            signs[:,j] = np.where(remainder@basis[j]>=0,1.,-1.)
        design = np.column_stack([np.ones(len(x)), signs])
        solved, *_ = np.linalg.lstsq(design, x, rcond=None)
        mean, basis = solved[0], solved[1:]
    return np.rint(np.vstack([mean, basis])*64).astype(np.int8)


def generate(parameters):
    bits = ((np.arange(64)[:,None] >> np.arange(B)) & 1).astype(np.int16)
    signs = 2*bits-1
    return parameters[0].astype(np.int16)+signs@parameters[1:].astype(np.int16)


def consume(parameters, labels, queries, scales):
    response = np.zeros((len(queries),len(labels)), np.int32)
    for s in range(labels.shape[1]):
        base = queries[:,s].astype(np.int32)@parameters[0].astype(np.int32)
        directions = queries[:,s].astype(np.int32)@parameters[1:].astype(np.int32).T
        # The 64-entry response table is generated by adds from just seven
        # projected parameters; weights are never reconstructed at consumption.
        signs = 2*((np.arange(64)[:,None] >> np.arange(B)) & 1)-1
        table = base[:,None] + (signs @ directions.T).T
        response += table[:,labels[:,s]]
    return response.astype(np.float64)/64*scales[None,:]


def main():
    study.LENGTH = L
    rng = np.random.default_rng(study.SEED)
    with np.load(study.FIXTURE) as z:
        w = z['trits'].reshape(5120,16,L).astype(np.float32)
        q = z['queries'].reshape(8,16,L).astype(np.int32)
        scales = z['scales_fp16'].astype(np.float64)
    x = w[:4096].reshape(-1,L)
    x = x[rng.choice(len(x),8192,replace=False)]
    parameters = fit(x)
    codes = generate(parameters)
    labels = np.empty((5120,16),np.int32)
    for s in range(16):
        labels[:,s] = study.distances(w[:,s],codes.astype(np.float32)/64).argmin(1)
    predicted = consume(parameters, labels, q, scales)
    independent = study.replay(codes, labels, q, scales)
    assert np.array_equal(predicted, independent), 'composed table differs from direct codeword response'
    random_q = rng.integers(-127,128,size=(32,16,L),dtype=np.int16).astype(np.int32)
    result={'format':'response-codebooks-algebraic/1', 'fixture_sha256':study.sha(study.FIXTURE),
            'script_sha256':study.sha(Path(__file__)), 'study_source_sha256':study.sha(Path(study.__file__)),
            'dictionary_bytes':parameters.nbytes, 'label_bytes':5120*12,
            'retained_scale_bytes':10240,
            'total_bits_per_weight':8*(parameters.nbytes+5120*12+10240)/(5120*128),
            'online_table_integer_products':16*7*8,
            'online_table_adds_at_most':16*64*6,
            'table_bytes':16*64*4, 'row_lookups':16,
            'train_query_train_row':study.evaluate(predicted[:4],w,q[:4],scales,slice(0,4096)),
            'held_query_held_row':study.evaluate(predicted[4:],w,q[4:],scales,slice(4096,None)),
            'synthetic_query_held_row':study.evaluate(consume(parameters,labels,random_q,scales),w,random_q,scales,slice(4096,None))}
    (HERE/'algebraic-results.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))


if __name__=='__main__':
    main()
