#!/usr/bin/env python3
"""Exact contraction of a gated FFN on T²; no hardware performance claim."""
from fractions import Fraction
from itertools import product
import json
from pathlib import Path
import random

POINTS = list(product((-1, 0, 1), repeat=2))


def features(x, y):
    return [x, y, x*x, y*y, x*y, x*x*y, x*y*y]


def contract(f):
    a, b, c, d = f(1, 0), f(-1, 0), f(0, 1), f(0, -1)
    e, h, i, j = f(1, 1), f(1, -1), f(-1, 1), f(-1, -1)
    assert f(0, 0) == 0
    assert e+h+i+j == 2*(a+b+c+d)
    return [2*(a-b), 2*(c-d), 2*(a+b), 2*(c+d),
            e-h-i+j, e-h+i-j-2*(c-d), e+h-i-j-2*(a-b)]


def rank(matrix):
    a = [[Fraction(x) for x in row] for row in matrix]
    k = 0
    for c in range(len(a[0])):
        p = next((r for r in range(k, len(a)) if a[r][c]), None)
        if p is None:
            continue
        a[p], a[k] = a[k], a[p]
        pivot = a[k][c]
        a[k] = [v/pivot for v in a[k]]
        for r in range(len(a)):
            if r != k:
                t = a[r][c]
                a[r] = [x-t*y for x, y in zip(a[r], a[k])]
        k += 1
    return k


def unit(w, x, y):
    a, b, c, d = w
    return max(a*x+b*y, 0)*(c*x+d*y)


def main():
    rng = random.Random(816372)
    trials = []
    for hidden in (1, 8, 64, 256):
        widths = [tuple(rng.choice((-1, 0, 1)) for _ in range(4)) for _ in range(hidden)]
        consumers = [[rng.choice((-1, 0, 1)) for _ in range(hidden)] for _ in range(4)]
        cs = []
        for consumer in consumers:
            def f(x, y):
                return sum(v*unit(w, x, y) for v, w in zip(consumer, widths))
            c = contract(f)
            for x, y in POINTS:
                assert sum(a*b for a, b in zip(c, features(x, y))) == 4*f(x, y)
            cs.append(c)
        trials.append({"hidden": hidden, "outputs": 4, "points": 9,
                       "weights": widths, "consumer": consumers,
                       "contracted_coefficients_for_4F": cs,
                       "largest_absolute_coefficient": max(abs(x) for c in cs for x in c),
                       "all_exact": True})

    # Every scalar ternary gate/up choice. Their span reaches all seven dimensions.
    units = list(product((-1, 0, 1), repeat=4))
    coefficients = [contract(lambda x, y: unit(w, x, y)) for w in units]
    feature_rank = rank([features(x, y) for x, y in POINTS])
    family_rank = rank(coefficients)
    assert feature_rank == family_rank == 7
    nontrit = {"input": [2, 0], "direct_4F": 16,
               "contracted_4F": sum(a*b for a, b in zip(contract(lambda x,y: max(x,0)*x), features(2,0)))}
    assert nontrit["contracted_4F"] == 12
    result = {"format": "kelana-contracted-map/1",
              "domain": "two ternary inputs, four integer outputs",
              "gate": "ReLU, which satisfies s(t)-s(-t)=t exactly",
              "arithmetic": "unbounded exact integers; no FP32 or native ISA equivalence claim",
              "construction": "seven coefficients per output, common monomials; represents 4F",
              "feature_rank_over_Q": feature_rank,
              "ternary_unit_family_rank_over_Q": family_rank,
              "ternary_units_checked": len(units),
              "trials": trials, "nontrit_counterexample": nontrit,
              "scope": "Hidden width disappears online. This is not a hardware speedup or an efficient whole-Bonsai representation: the ternary input dimension is only two."}
    path = Path(__file__).with_name("result.json")
    path.write_text(json.dumps(result, indent=2)+"\n")
    trial = trials[2]
    rows = ["  ⟨"+", ".join(map(str, (*w, c)))+"⟩"
            for w, c in zip(trial["weights"], trial["consumer"][2])]
    lean = '''-- Generated by research/ffn/contracted-map/check.py.
import Kelana.ContractedFFN
import Kelana.Hardware.IntOps
import Kelana.TritObserver

namespace Kelana.ContractedToy
open Kelana.ContractedFFN Kelana.Hardware

def weights : List (Unit Int) := [
'''+",\n".join(rows)+''']

def nibblePack : List Int → BitVec 32
  | [] => 0
  | x :: xs => (BitVec.ofInt 32 x &&& 15) ||| (nibblePack xs <<< 4)

def featureWord (x y : Int) : BitVec 32 :=
  nibblePack [x, y, x*x, y*y, x*y, x*x*y, x*y*y, 0]

def coefficientWord : BitVec 32 := nibblePack [0, -5, 0, 1, 1, 1, -2, 0]

def run (x y : Int) : Lane32 :=
  v_dot8_i32_iu4 { neg := 3 } coefficientWord (featureWord x y) 0

/-- All 64 hidden units have disappeared from this hardware expression.
Feature encoding is separate, input-dependent work; this is not a claim that the
whole program is one instruction or that it is optimal. Output is 2F. -/
theorem dot_replaces_network : ∀ x y : Fin 3,
    run (Int.ofNat x.val-1) (Int.ofNat y.val-1) =
      .ok (BitVec.ofInt 32 (2*network relu weights (Int.ofNat x.val-1) (Int.ofNat y.val-1))) := by
  decide +kernel

/-- Eight prepared bytes replace the whole observed function, including its
feature encoder. This output is a byte; sign extension is outside the contract. -/
def outputByte (x y : Fin 3) : BitVec 8 :=
  BitVec.ofInt 8 (2*network relu weights (Int.ofNat x.val-1) (Int.ofNat y.val-1))

theorem two_instructions_replace_network : ∀ x y : Fin 3,
    Kelana.TritObserver.run outputByte x y = .ok (outputByte x y) :=
  Kelana.TritObserver.observer_compilation outputByte (by decide +kernel)

end Kelana.ContractedToy
'''
    root = Path(__file__).resolve().parents[3]
    (root / "Kelana/ContractedToy.lean").write_text(lean)
    print(f"81 unit maps, rank {family_rank}; four networks, 144 output cases exact; nontrit counterexample retained")


if __name__ == "__main__":
    main()
