#!/usr/bin/env python3
"""Generate the Lean instruction catalogue from the pinned AMD ISA XML.

Reads sources/amdgpu_isa_rdna3_5.xml, formalization.json and eligibility.json; writes the
modules under Kelana/Hardware/Catalogue/. Standard library only, no network access, and no
hand-maintained instruction list: every name, group, encoding and signature comes from the
XML. `--check` regenerates in memory and reports any file that differs.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

LEAN = Path(__file__).resolve().parent
GFX = LEAN.parent
ROOT = GFX.parent.parent
XML = GFX / "sources/amdgpu_isa_rdna3_5.xml"
MANUAL = GFX / "sources/rdna35-isa.txt"
MANIFEST = LEAN / "formalization.json"
ELIGIBILITY = LEAN / "eligibility.json"
OUT = ROOT / "Kelana/Hardware/Catalogue"
COMMAND = "python3 hardware/gfx1151/lean/generate.py"

GROUPS = {
    "VALU": ("valu", "VALU"), "VMEM": ("vmem", "VMEM"), "SALU": ("salu", "SALU"),
    "BRANCH": ("branch", "Other"), "WAVE_CONTROL": ("waveControl", "Other"),
    "SMEM": ("smem", "Other"), "MESSAGE": ("message", "Other"),
    "TRAP": ("trap", "Other"), "EXPORT": ("«export»", "Other"),
}
CHUNK = 100


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def quote(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def strings(values):
    return "#[" + ", ".join(quote(v) for v in values) + "]"


def signature(encoding):
    inputs, outputs = [], []
    for operand in encoding.findall("Operands/Operand"):
        name = operand.findtext("FieldName") or operand.findtext("OperandType")
        fmt = operand.findtext("DataFormatName").removeprefix("FMT_")
        width = operand.findtext("OperandSize")
        implicit = "*" if operand.get("IsImplicit") == "true" else ""
        item = f"{name}{implicit}:{fmt}[{width}]"
        if operand.get("Input") == "true":
            inputs.append(item)
        if operand.get("Output") == "true":
            outputs.append(item)
    return ", ".join(inputs) + " -> " + ", ".join(outputs)


def deduplicate(values):
    return list(dict.fromkeys(values))


def status_term(entry):
    if entry is None:
        return ".unformalized"
    return (".laneBitVec " + quote(entry["decl"]) + " " + quote(entry["pseudocode"])
            + " " + quote(entry["modeled"]) + " " + quote(entry["unmodeled"]))


def probes_term(probes):
    return "#[" + ", ".join(
        "⟨" + quote(p["form"]) + ", " + ("true" if p["accepted"] else "false")
        + ", " + quote(p["detail"]) + "⟩" for p in probes) + "]"


def instruction_term(node, modeled, probes):
    name = node.findtext("InstructionName")
    group = GROUPS[node.findtext("FunctionalGroup/Name")][0]
    subgroup = node.findtext("FunctionalSubgroup/Name")
    aliases = [a.text for a in node.findall("AliasedInstructionNames/InstructionName")]
    encodings = deduplicate(e.findtext("EncodingName")
                            for e in node.findall("InstructionEncodings/InstructionEncoding"))
    signatures = deduplicate(signature(e)
                             for e in node.findall("InstructionEncodings/InstructionEncoding"))
    subgroup_term = "none" if subgroup is None else f"(some {quote(subgroup)})"
    return ("⟨" + quote(name) + f", .{group}, " + subgroup_term + ", " + strings(aliases)
            + ", " + strings(encodings) + ", " + strings(signatures) + ", "
            + status_term(modeled.get(name)) + ", " + probes_term(probes.get(name, []))
            + "⟩")


def header(module, extra_imports=()):
    imports = "\n".join(f"import {i}" for i in ("Kelana.Hardware.Catalogue.Record",) + tuple(extra_imports))
    return (f"/- Generated by `{COMMAND}`. Do not edit. -/\n{imports}\n\n"
            f"namespace Kelana.Hardware.Catalogue.{module}\n\n")


def data_module(module, terms):
    body = header(module)
    chunks = [terms[i:i + CHUNK] for i in range(0, len(terms), CHUNK)] or [[]]
    for index, chunk in enumerate(chunks):
        body += f"def part{index} : Array Instruction := #[\n"
        body += ",\n".join("  " + term for term in chunk)
        body += "]\n\n"
    body += ("def all : Array Instruction :=\n  "
             + " ++ ".join(f"part{i}" for i in range(len(chunks))) + "\n\n")
    body += f"end Kelana.Hardware.Catalogue.{module}\n"
    return body


def index_module(modules, provenance, questions):
    body = "/- Generated by `" + COMMAND + "`. Do not edit. -/\n"
    body += "\n".join(f"import Kelana.Hardware.Catalogue.{m}" for m in modules) + "\n\n"
    body += "namespace Kelana.Hardware.Catalogue\n\n"
    body += "/-- Source hashes, counts and the command that regenerates this catalogue. -/\n"
    body += "def provenance : Provenance := ⟨\n"
    body += ",\n".join("  " + v for v in [
        quote(provenance["architecture"]), quote(provenance["releaseDate"]),
        quote(provenance["schemaVersion"]), quote(provenance["isaXmlSha256"]),
        quote(provenance["manualTextSha256"]), quote(provenance["formalizationManifestSha256"]),
        quote(provenance["eligibilityProbeSha256"]), quote(COMMAND),
        str(provenance["instructionCount"]), str(provenance["encodingRecordCount"])])
    body += "⟩\n\n"
    body += ("/-- Every architecture-level instruction name of AMD RDNA 3.5, with Kelana's status\n"
             "for each. Membership is an architecture claim; see `Instruction.gfx1151Probes` for\n"
             "what the installed gfx1151 assembler was observed to accept. -/\n")
    body += "def all : Array Instruction :=\n  " + " ++ ".join(f"{m}.all" for m in modules) + "\n\n"
    body += ("/-- Questions the pinned sources leave open, kept as data so that a meaning Kelana\n"
             "does not have stays visible instead of turning into a default. -/\n")
    body += "def openQuestions : Array String := #[\n"
    body += ",\n".join("  " + quote(q) for q in questions) + "]\n\n"
    body += "end Kelana.Hardware.Catalogue\n"
    return body


def linkage_module(modeled):
    body = ("/- Generated by `" + COMMAND + "`. Do not edit.\n\n"
            "Elaborating this module fails if a `Status.laneBitVec` declaration named in the\n"
            "catalogue does not exist, so the status table cannot drift from the Lean meanings. -/\n"
            "import Kelana.Hardware.IntOps\n\nnamespace Kelana.Hardware.Catalogue.Linkage\n\n")
    for entry in modeled:
        body += f"example := @{entry['decl']}\n"
    body += "\nend Kelana.Hardware.Catalogue.Linkage\n"
    return body


def build():
    isa = ET.parse(XML).getroot().find("ISA")
    document = ET.parse(XML).getroot().find("Document")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    eligibility = json.loads(ELIGIBILITY.read_text(encoding="utf-8"))

    instructions = list(isa.find("Instructions"))
    names = {node.findtext("InstructionName") for node in instructions}
    modeled = {entry["instruction"]: entry for entry in manifest["modeled"]}
    unknown = sorted((set(modeled) | {p["instruction"] for p in eligibility["probes"]}) - names)
    if unknown:
        raise SystemExit(f"Not instruction names in the pinned ISA: {', '.join(unknown)}")

    probes = {}
    for probe in eligibility["probes"]:
        probes.setdefault(probe["instruction"], []).append(probe)

    files = {}
    modules = ["VALU", "VMEM", "SALU", "Other"]
    for module in modules:
        terms = [instruction_term(node, modeled, probes) for node in instructions
                 if GROUPS[node.findtext("FunctionalGroup/Name")][1] == module]
        files[OUT / f"{module}.lean"] = data_module(module, terms)

    provenance = {
        "architecture": isa.findtext("Architecture/ArchitectureName"),
        "releaseDate": document.findtext("ReleaseDate"),
        "schemaVersion": document.findtext("SchemaVersion"),
        "isaXmlSha256": sha256(XML),
        "manualTextSha256": sha256(MANUAL),
        "formalizationManifestSha256": sha256(MANIFEST),
        "eligibilityProbeSha256": sha256(ELIGIBILITY),
        "instructionCount": len(instructions),
        "encodingRecordCount": sum(len(node.find("InstructionEncodings")) for node in instructions),
    }
    files[OUT / "Index.lean"] = index_module(modules, provenance, manifest["openQuestions"])
    files[OUT / "Linkage.lean"] = linkage_module(manifest["modeled"])
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report differences instead of writing")
    args = parser.parse_args()
    files = build()
    stale = []
    for path, text in files.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print("stale: " + ", ".join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
        return 1
    print(("checked " if args.check else "wrote ")
          + ", ".join(str(p.relative_to(ROOT)) for p in files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
