import Kelana.TernaryAlgebra

-- Input SHA-256: eaf5308bce7a2b032cd0230b4dd9faeb2b5d11ec74118a3a5e3da3599bc779ec
-- Generated by research/discovery/certificates/export_lean.py.
-- Both original expressions are evaluated in exact rational arithmetic.
namespace Map_eaf5308bce7a2b03
open Kelana.TernaryAlgebra

def lhs : Expr Rat 2 := (.times (.times (.plus (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩)) (.plus (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩))) (.times (.plus (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩)) (.plus (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩))))
def rhs : Expr Rat 2 := (.plus (.plus (.plus (.plus (.lit (0 : Rat)) (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩))) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩))) (.times (.lit (8 : Rat)) (.times (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩)))) (.times (.lit (6 : Rat)) (.times (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩)))))

theorem normal_forms_equal : lhs.normalize = rhs.normalize := by decide +kernel

theorem discovered_identity (x : Fin 2 → Rat) (hx : CubicGrid x) :
    lhs.eval x = rhs.eval x :=
  equivalent_of_normal_equal lhs rhs normal_forms_equal x hx

#print axioms discovered_identity
end Map_eaf5308bce7a2b03
