import Kelana.TernaryAlgebra

-- Input SHA-256: 8865ff7d3837571dd7b5900629e172c60dad9c452b88900771d73db1616afb06
-- Generated by research/discovery/certificates/export_lean.py.
-- Both original expressions are evaluated in exact rational arithmetic.
namespace Map_8865ff7d3837571d
open Kelana.TernaryAlgebra

def lhs : Expr Rat 2 := (.times (.times (.lit ((1 / 2) : Rat)) (.plus (.plus (.plus (.plus (.plus (.plus (.lit (0 : Rat)) (.var ⟨0, by decide⟩)) (.var ⟨1, by decide⟩)) (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩))) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩))) (.times (.var ⟨0, by decide⟩) (.var ⟨1, by decide⟩))) (.times (.lit (-1 : Rat)) (.times (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩)))))) (.plus (.var ⟨0, by decide⟩) (.times (.lit (-1 : Rat)) (.var ⟨1, by decide⟩))))
def rhs : Expr Rat 2 := (.times (.lit ((1 / 2) : Rat)) (.plus (.plus (.plus (.plus (.plus (.plus (.lit (0 : Rat)) (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩))) (.times (.lit (-1 : Rat)) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩)))) (.var ⟨0, by decide⟩)) (.times (.lit (-1 : Rat)) (.var ⟨1, by decide⟩))) (.times (.lit (-1 : Rat)) (.times (.var ⟨0, by decide⟩) (.times (.var ⟨1, by decide⟩) (.var ⟨1, by decide⟩))))) (.times (.times (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨1, by decide⟩))))

theorem normal_forms_equal : lhs.normalize = rhs.normalize := by decide +kernel

theorem discovered_identity (x : Fin 2 → Rat) (hx : CubicGrid x) :
    lhs.eval x = rhs.eval x :=
  equivalent_of_normal_equal lhs rhs normal_forms_equal x hx

#print axioms discovered_identity
end Map_8865ff7d3837571d
